name: PEO
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - openmm=7.7
  - openmmtools=0.21
  - parmed=3.4
  - mdtraj=1.9
  - numpy=1.21
  - scipy=1.7
  - packmol=20
  - notebook=6.4
  - matplotlib=3.2
