name: PEO
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - openmm=8.0
  - parmed=3.4
  - mdtraj=1.9
  - numpy=1.21
  - scipy=1.7
  - packmol=20.14
  - notebook=6.4
  - matplotlib=3.2
